# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: orders-postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql


version: '3.8'

services:
  db:
    image: postgres:15
    container_name: orders-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: orders-backend
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: db
      PGPORT: 5432
      PORT: 4000
    volumes:
      - ./backend:/app
