version: '3.8'

services:
  db:
    image: postgres:15
    container_name: orders-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: orders-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app

  frontend:
    container_name: orders-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80' 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
